export const INITIALIZE_TOKENS = 'INIT_TOKENS';
export const SET_TOKEN_LIST = 'BRIDGE_SET_TOKEN_LIST';
export const SET_SELECTED_ASSET = 'BRIDGE_SET_SELECTED_ASSET';
export const SET_DEPOSIT_AMOUNT = 'BRIDGE_SET_DEPOSIT_AMOUNT';
export const SET_SWAP_DIRECTION = 'BRIDGE_SET_SWAP_DIRECTION;';
export const SET_SHOW_CONFIRM_TRANSACTION_MODAL = 'BRIDGE_SET_SHOW_CONFIRMATION_MODAL';
