export const SET_CONTRACT_ADDRESS = 'ERC20_SET_CONTRACT_ADDRESS';
export const CREATE_CONTRACT_INSTANCE = 'ERC20_CREATE_CONTRACT_INSTANCE';
export const SET_TOKEN_ALLOWANCE = 'ERC20_SET_TOKEN_ALLOWANCE';
export const SET_TOKEN_BALANCE = 'ERC20_SET_TOKEN_BALANCE'
export const SET_TOKEN_NAME = 'ERC20_SET_TOKEN_NAME';
