export const SET_NET = 'SET_NET';
export const SET_METAMASK_FOUND = 'SET_METAMASK_FOUND';
export const SET_METAMASK_CONNECTED = 'SET_METAMASK_CONNECTED';
export const SET_METAMASK_MISSING = 'SET_METAMASK_MISSING';
export const SET_METAMASK_NETWORK = 'SET_METAMASK_NETWORK';
export const SET_POLKADOTJS_FOUND = 'SET_POLKADOTJS_FOUND';
export const SET_POLKADOTJS_CONNECTED = 'SET_POLKADOTJS_CONNECTED';
export const SET_POLKADOTJS_MISSING = 'SET_POLKADOTJS_MISSING';
