export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_CONFIRMATIONS = 'UPDATE_CONFIRMATIOS';
export const SET_TRANSACTION_STATUS = 'TRANSACTION_STATUS';
export const POLKA_ETH_MINTED = 'POLKA_ETH_MINTED';
export const POLKA_ETH_BURNED = 'POLKA_ETH_BURNED';
export const SET_PENDING_TRANSACTION = 'SET_PENDING_TRANSACTION';
export const ETH_UNLOCKED_EVENT = 'ETH_UNLOCKED_EVENT';